### PR TITLE
Mint login form

### PR DESCRIPTION
**Pull request by SlowKingV**
Final revision by us for review.

### CODE REVIEW

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello @SlowKingV @techbabouche 👋 you have done a good job in this project, Only thing is remaining is you have to write a descriptive readme with description, technology used, author, demo link like that.

----
### Don't forgot to request for another code review 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack_

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!

### Nice job! Project looks! :+1:  Readme file is very descriptive now!!!

### But need only fix  linter before the project can be approved

* Linter now is not working :(
You can read more here: [Set up a code linter.](https://github.com/microverseinc/linters-config/tree/master/css)

linter


Great that you use  the  [`<nav>` tag](http://html5doctor.com/nav-element/)  and the [`<footer>`](https://www.w3schools.com/TagS/tag_footer.asp) tag for the footer, but not bad to use of a [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` in HTML document too. Maybe in the next project, you can try.

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

*Happy coding 😄*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
Linter is not working.

**Comment by SlowKingV** [comment]
I don't know why Stickler wants us to change the order of CSS in a strange way but everything else is correct now.

**Comment by Anna-Myzukina** [comment]
It shows the next errors:



As you can see problems in file css 




Try to fix them and your project will be approved.

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
Linter shows errors in the project

**Review by nikasulo — APPROVED** [review]
# Great work guys! @SlowKingV @Joecleverman :rocket:
You may merge!

**Comment by techbabouche** [comment]
Thank you!
    On Thursday, November 28, 2019, 04:52:38 PM EST, Tolulope Oluwadamilare Olusakin <notifications@github.com> wrote:  
 
 
@Oluwadamilareolusakin approved this pull request.

Great work guys! @SlowKingV @Joecleverman 🚀
 
You may merge!

**Pull request merged**
